// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using AlteredOwnership.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlteredOwnership.Server.Data.Migrations
{
    [DbContext(typeof(OwnershipDbContext))]
    [Migration("20260531112026_AddCardsCatalog")]
    partial class AddCardsCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlteredOwnership.Server.Data.Entities.Card", b =>
                {
                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Faction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Forest")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<int?>("MainCost")
                        .HasColumnType("integer");

                    b.Property<int?>("Mountain")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("Ocean")
                        .HasColumnType("integer");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RecallCost")
                        .HasColumnType("integer");

                    b.Property<string>("Set")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("SubTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Variation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Reference");

                    b.HasIndex("CardType");

                    b.HasIndex("Faction");

                    b.HasIndex("Rarity");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("AlteredOwnership.Server.Data.Entities.CardOwnership", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CardReference")
                        .HasColumnType("text");

                    b.Property<bool>("IsUnique")
                        .HasColumnType("boolean");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "CardReference");

                    b.HasIndex("CardReference")
                        .IsUnique()
                        .HasFilter("\"IsUnique\" = true");

                    b.ToTable("CardOwnerships", t =>
                        {
                            t.HasCheckConstraint("CK_CardOwnerships_UniqueQuantityOne", "(\"IsUnique\" = false) OR (\"Quantity\" = 1)");
                        });
                });

            modelBuilder.Entity("AlteredOwnership.Server.Data.Entities.OwnershipEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PayloadHash")
                        .HasColumnType("text");

                    b.Property<int>("UserEventId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PayloadHash")
                        .IsUnique()
                        .HasFilter("\"PayloadHash\" IS NOT NULL");

                    b.HasIndex("UserId", "UserEventId")
                        .IsUnique();

                    b.ToTable("OwnershipEvents");
                });

            modelBuilder.Entity("AlteredOwnership.Server.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KeycloakId")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
